var Nette;
(function(h){var c=function(a){this.length=0;if("string"===typeof a)a=this._find(document,a);else if(!a||a.nodeType||void 0===a.length||a===window)a=[a];for(var b=0,e=a.length;b<e;b++)a[b]&&(this[this.length++]=a[b])};c.factory=function(a){return new c(a)};c.prototype.find=function(a){return new c(this._find(this[0],a))};c.prototype._find=function(a,b){if(!a||!b)return[];if(document.querySelectorAll)return a.querySelectorAll(b);if("#"===b.charAt(0))return[document.getElementById(b.substring(1))];var b=
b.split("."),e=a.getElementsByTagName(b[0]||"*");if(b[1]){for(var d=[],f=RegExp("(^|\\s)"+b[1]+"(\\s|$)"),g=0,c=e.length;g<c;g++)f.test(e[g].className)&&d.push(e[g]);return d}return e};c.prototype.dom=function(){return this[0]};c.prototype.each=function(a){for(var b=0;b<this.length&&!1!==a.apply(this[b]);b++);return this};c.prototype.bind=function(a,b){if(document.addEventListener&&("mouseenter"===a||"mouseleave"===a))var e=b,a="mouseenter"===a?"mouseover":"mouseout",b=function(a){for(var b=a.relatedTarget;b;b=
b.parentNode)if(b===this)return;e.call(this,a)};return this.each(function(){var e=this,f=e.nette?e.nette:e.nette={},f=f.events=f.events||{};if(!f[a]){var c=f[a]=[],i=function(a){a.target||(a.target=a.srcElement);a.preventDefault||(a.preventDefault=function(){a.returnValue=false});a.stopPropagation||(a.stopPropagation=function(){a.cancelBubble=true});a.stopImmediatePropagation=function(){this.stopPropagation();b=c.length};for(var b=0;b<c.length;b++)c[b].call(e,a)};document.addEventListener?e.addEventListener(a,
i,!1):document.attachEvent&&e.attachEvent("on"+a,i)}f[a].push(b)})};c.prototype.addClass=function(a){return this.each(function(){this.className=this.className.replace(/^|\s+|$/g," ").replace(" "+a+" "," ")+" "+a})};c.prototype.removeClass=function(a){return this.each(function(){this.className=this.className.replace(/^|\s+|$/g," ").replace(" "+a+" "," ")})};c.prototype.hasClass=function(a){return this[0]&&-1<this[0].className.replace(/^|\s+|$/g," ").indexOf(" "+a+" ")};c.displays={};c.prototype.show=
function(){return this.each(function(){var a=this.tagName;c.displays[a]||(c.displays[a]=(new c(document.body.appendChild(document.createElement(a)))).css("display"));this.style.display=c.displays[a]})};c.prototype.hide=function(){return this.each(function(){this.style.display="none"})};c.prototype.css=function(a){if(this[0]&&this[0].currentStyle)return this[0].currentStyle[a];if(this[0]&&window.getComputedStyle)return document.defaultView.getComputedStyle(this[0],null).getPropertyValue(a)};c.prototype.data=
function(){if(this[0])return this[0].nette?this[0].nette:this[0].nette={}};c.prototype.val=function(){var a=this[0];if(a)if(a.nodeName){if("select"===a.nodeName.toLowerCase()){var b=a.selectedIndex,e=a.options;if(0>b)return null;if("select-one"===a.type)return e[b].value;b=0;a=[];for(d=e.length;b<d;b++)e[b].selected&&a.push(e[b].value);return a}if("checkbox"===a.type)return a.checked;if(a.value)return a.value.replace(/^\s+|\s+$/g,"")}else{for(var b=0,d=a.length;b<d;b++)if(this[b].checked)return this[b].value;
return null}};c.prototype.trav=function(a,b,e){for(b=b.split(".");a&&!(1===a.nodeType&&(!b[0]||a.tagName.toLowerCase()===b[0])&&(!b[1]||(new c(a)).hasClass(b[1])));)a=a[e];return new c(a||[])};c.prototype.closest=function(a){return this.trav(this[0],a,"parentNode")};c.prototype.prev=function(a){return this.trav(this[0]&&this[0].previousSibling,a,"previousSibling")};c.prototype.next=function(a){return this.trav(this[0]&&this[0].nextSibling,a,"nextSibling")};c.prototype.offset=function(a){if(a)return this.each(function(){for(var b=
this,e=-a.left||0,c=-a.top||0;b=b.offsetParent;)e+=b.offsetLeft,c+=b.offsetTop;this.style.left=-e+"px";this.style.top=-c+"px"});if(this[0]){for(var b=this[0],e={left:b.offsetLeft,top:b.offsetTop};b=b.offsetParent;)e.left+=b.offsetLeft,e.top+=b.offsetTop;return e}};c.prototype.position=function(a){if(a)return this.each(function(){this.nette&&this.nette.onmove&&this.nette.onmove.call(this,a);for(var b in a)this.style[b]=a[b]+"px"});if(this[0])return{left:this[0].offsetLeft,top:this[0].offsetTop,right:this[0].style.right?
parseInt(this[0].style.right,10):0,bottom:this[0].style.bottom?parseInt(this[0].style.bottom,10):0,width:this[0].offsetWidth,height:this[0].offsetHeight}};c.dragging=!1;c.prototype.draggable=function(a){var b=this[0],e=document.documentElement,d,a=a||{};(a.handle?new c(a.handle):this).bind("mousedown",function(f){var g=new c(a.handle?b:this);f.preventDefault();f.stopPropagation();if(c.dragging)return e.onmouseup(f);var i=g.position(),h=a.rightEdge?i.right+f.clientX:i.left-f.clientX,j=a.bottomEdge?
i.bottom+f.clientY:i.top-f.clientY;c.dragging=!0;d=!1;e.onmousemove=function(b){b=b||event;d||(a.draggedClass&&g.addClass(a.draggedClass),a.start&&a.start(b,g),d=!0);var e={};e[a.rightEdge?"right":"left"]=a.rightEdge?h-b.clientX:b.clientX+h;e[a.bottomEdge?"bottom":"top"]=a.bottomEdge?j-b.clientY:b.clientY+j;g.position(e);return!1};e.onmouseup=function(b){d&&(a.draggedClass&&g.removeClass(a.draggedClass),a.stop&&a.stop(b||event,g));c.dragging=e.onmousemove=e.onmouseup=null;return!1}}).bind("click",
function(a){d&&a.stopImmediatePropagation()});return this};h.Query=c})(Nette||(Nette={}));
(function(h){var c=h.Debug||(h.Debug={}),a=h.Query.factory,b=function(b){this.id="nette-debug-panel-"+b;this.elem=a("#"+this.id)};b.PEEK="nette-mode-peek";b.FLOAT="nette-mode-float";b.WINDOW="nette-mode-window";b.FOCUSED="nette-focused";b.zIndex=2E4;b.get=function(a){return new b(a)};b.toggle=function(b){var d=b.rel,d="#"===d.charAt(0)?a(d):a(b).next(d.substring(4));"none"===d.css("display")?(d.show(),b.innerHTML=b.innerHTML.replace("\u25ba","\u25bc")):(d.hide(),b.innerHTML=b.innerHTML.replace("\u25bc",
"\u25ba"))};b.prototype.init=function(){var b=this;this.elem.data().onmove=function(a){b.moveConstrains(a)};a(window).bind("resize",function(){b.reposition()});this.elem.draggable({rightEdge:!0,bottomEdge:!0,handle:this.elem.find("h1"),stop:function(){b.toFloat()}}).bind("mouseenter",function(){b.focus()}).bind("mouseleave",function(){b.blur()});this.initToggler();b=this;this.elem.find(".nette-icons").find("a").bind("click",function(a){"close"===this.rel?b.toPeek():b.toWindow();a.preventDefault()});
this.restorePosition()};b.prototype.is=function(a){return this.elem.hasClass(a)};b.prototype.focus=function(){var a=this.elem;this.is(b.WINDOW)?a.data().win.focus():(clearTimeout(a.data().blurTimeout),a.addClass(b.FOCUSED).show(),a[0].style.zIndex=b.zIndex++)};b.prototype.blur=function(){var a=this.elem;a.removeClass(b.FOCUSED);this.is(b.PEEK)&&(a.data().blurTimeout=setTimeout(function(){a.hide()},50))};b.prototype.toFloat=function(){this.elem.removeClass(b.WINDOW).removeClass(b.PEEK).addClass(b.FLOAT).show();
this.reposition()};b.prototype.toPeek=function(){this.elem.removeClass(b.WINDOW).removeClass(b.FLOAT).addClass(b.PEEK).hide();document.cookie=this.id+"=; path=/"};b.prototype.toWindow=function(){var e=this,d=this.elem.offset();d.left+="number"===typeof window.screenLeft?window.screenLeft:window.screenX+10;d.top+="number"===typeof window.screenTop?window.screenTop:window.screenY+50;var c=window.open("",this.id.replace(/-/g,"_"),"left="+d.left+",top="+d.top+",width="+d.width+",height="+(d.height+15)+
",resizable=yes,scrollbars=yes");if(c){d=c.document;d.write('<!DOCTYPE html><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style>'+a("#nette-debug-style").dom().innerHTML+"</style><script>"+a("#nette-debug-script").dom().innerHTML+'<\/script><body id="nette-debug">');d.body.innerHTML='<div class="nette-panel nette-mode-window" id="'+this.id+'">'+this.elem.dom().innerHTML+"</div>";var g=c.Nette.DebugPanel.get(this.id.replace("nette-debug-panel-",""));g.initToggler();g.reposition();
d.title=this.elem.find("h1").dom().innerHTML;a([c]).bind("unload",function(){e.toPeek();c.close()});a(d).bind("keyup",function(a){27===a.keyCode&&(!a.shiftKey&&!a.altKey&&!a.ctrlKey&&!a.metaKey)&&c.close()});document.cookie=this.id+"=window; path=/";this.elem.hide().removeClass(b.FLOAT).removeClass(b.PEEK).addClass(b.WINDOW).data().win=c}};b.prototype.reposition=function(){if(this.is(b.WINDOW)){var a=document.documentElement;window.resizeBy(a.scrollWidth-a.clientWidth,a.scrollHeight-a.clientHeight)}else a=
this.elem.position(),a.width&&(this.elem.position({right:a.right,bottom:a.bottom}),document.cookie=this.id+"="+a.right+":"+a.bottom+"; path=/")};b.prototype.moveConstrains=function(a){var b=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,c=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight,g=this.elem[0];a.right=Math.min(Math.max(a.right,-0.2*g.offsetWidth),b-0.8*g.offsetWidth);a.bottom=Math.min(Math.max(a.bottom,-0.2*g.offsetHeight),
c-g.offsetHeight)};b.prototype.initToggler=function(){var e=this;this.elem.bind("click",function(c){var f=a(c.target).closest("a").dom();f&&f.rel&&(b.toggle(f),c.preventDefault(),e.reposition())})};b.prototype.restorePosition=function(){var a=document.cookie.match(RegExp(this.id+"=(window|(-?[0-9]+):(-?[0-9]+))"));a&&a[2]?(this.toFloat(),this.elem.position({right:a[2],bottom:a[3]})):a?this.toWindow():this.elem.addClass(b.PEEK)};c.Panel=b;h=function(){this.id="nette-debug-bar"};h.prototype.init=function(){var c=
this,d=a("#"+this.id);d.data().onmove=function(a){c.moveConstrains(a)};a(window).bind("resize",function(){d.position({right:d.position().right,bottom:d.position().bottom})});d.draggable({rightEdge:!0,bottomEdge:!0,draggedClass:"nette-dragged",stop:function(){c.savePosition()}});c=this;d.find("a").bind("click",function(a){if("close"===this.rel)c.close();else if(this.rel){var d=b.get(this.rel);a.shiftKey?(d.toFloat(),d.toWindow()):d.is(b.FLOAT)?d.toPeek():(d.toFloat(),d.elem.position({right:d.elem.position().right+
Math.round(100*Math.random())+20,bottom:d.elem.position().bottom+Math.round(100*Math.random())+20}))}a.preventDefault()}).bind("mouseenter",function(){if(this.rel&&"close"!==this.rel&&!d.hasClass("nette-dragged")){var c=b.get(this.rel),e=a(this);c.focus();c.is(b.PEEK)&&c.elem.position({right:c.elem.position().right-e.offset().left+c.elem.position().width-e.position().width-4+c.elem.offset().left,bottom:c.elem.position().bottom-d.offset().top+c.elem.position().height+4+c.elem.offset().top})}}).bind("mouseleave",
function(){this.rel&&("close"!==this.rel&&!d.hasClass("nette-dragged"))&&b.get(this.rel).blur()});this.restorePosition();d.find("a").each(function(){this.rel&&"close"!==this.rel&&b.get(this.rel).init()})};h.prototype.close=function(){a("#nette-debug").hide();window.opera&&a("body").show()};h.prototype.moveConstrains=function(b){var c=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,f=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight,
g=a("#"+this.id)[0];b.right=Math.min(Math.max(b.right,0),c-g.offsetWidth);b.bottom=Math.min(Math.max(b.bottom,0),f-g.offsetHeight)};h.prototype.savePosition=function(){var b=a("#"+this.id).position();document.cookie=this.id+"="+b.right+":"+b.bottom+"; path=/"};h.prototype.restorePosition=function(){var b=document.cookie.match(RegExp(this.id+"=(-?[0-9]+):(-?[0-9]+)"));b&&a("#"+this.id).position({right:b[1],bottom:b[2]})};c.Bar=h})(Nette||(Nette={}));
